<?php
$CONFIG = array (
  'instanceid' => 'ocqq2wfk3kz9',
  'passwordsalt' => 'OB9x3KeztMpmdePsJIUzLIYVT4xbaK',
  'secret' => 'i4XXZZTN1hyEu6KliWcfWOqRPvu5OGCluL42seXu8nkXOWQ8',
  'trusted_domains' => 
  array (
    0 => '103.233.157.243',
    1 => 'smartcloud.myrangrang.com',
  ),
  'datadirectory' => '/home/smartbox/data',
  'overwrite.cli.url' => 'https://smartcloud.myrangrang.com',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'dbsmartbox',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_trlx',
  'dbpassword' => 'axrubkhvhz0xxa31y8lt3v532hxfj7',
  'installed' => true,
  'forcessl' => false,
  'forceSSLforSubdomains' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'root',
  'mail_domain' => 'smartcloud.myrangrang.com',
  'mail_smtphost' => 'smartcloud.myrangrang.com',
  'mail_smtpport' => '220',
  'loglevel' => 0,
  'appstoreenabled' => false,
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'preview_max_filesize_image' => 50,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => '',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
  ),
);
